# Generated by Django 5.2.17 on 2026-09-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('PRODUCT', 'Product & Engineering'), ('DESIGN', 'UI/UX & Brand Design'), ('MARKETING', 'Marketing & Growth'), ('OPERATIONS', 'Client & Operations'), ('INFRA', 'Security & Infrastructure')], default='PRODUCT', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#6366F1', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / In Progress'), ('PLANNING', 'Planning & Discovery'), ('ON_HOLD', 'On Hold / Paused'), ('COMPLETED', 'Completed / Shipped')], default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
